//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoriaPreguntasFrecuentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categoriaPreguntasFrecuentes()
        {
            this.preguntasFrecuentes = new HashSet<preguntasFrecuentes>();
        }
    
        public int categoriaPreguntaFreID { get; set; }
        public Nullable<int> empleadoID { get; set; }
        public string nombreCategoria { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preguntasFrecuentes> preguntasFrecuentes { get; set; }
    }
}
