//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.categoriaPreguntasFrecuentes = new HashSet<categoriaPreguntasFrecuentes>();
        }
    
        public int empleadoID { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string ApMaterno { get; set; }
        public Nullable<int> Edad { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categoriaPreguntasFrecuentes> categoriaPreguntasFrecuentes { get; set; }
    }
}
